### ISSUE TITLE
Rename "test.bas" to "qubic.bas"

### ISSUE THREAD

**Issue by maurymarkowitz** [GReaperEx/bcg#2] opened 2019-08-12 20:03 UTC
This file appears to have not be renamed correctly, the name inside is qubic.

**Comment by GReaperEx** [comment] 2019-08-13 04:55
Hmm, I did a diff on qubit.bas and test.bas, and their only real difference is at line #1560. I think it is safe to remove test.bas as a duplicate of qubit.bas, and rename the latter to qubic.bas

**Closed as completed** 2019-08-13 04:58 UTC
